services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-bot
    restart: unless-stopped
    env_file: .env
    tty: true
    volumes:
      - ./logs:/bot/logs
