services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    restart: unless-stopped
    env_file: .env
    tty: true
    volumes:
      - ./logs:/bot/logs
      - ./src/cogs:/bot/src/cogs
